/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logica.Revisiones;
import Logica.Statements;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author lumontero
 */
public class jdAsociarParteProovedor extends javax.swing.JDialog {

    /**
     * Creates new form jdAsociarParteProovedor
     */
    DefaultListModel modelParte = new DefaultListModel();
    DefaultListModel modelParteIds = new DefaultListModel();

    DefaultListModel modelProveedores = new DefaultListModel();

    public jdAsociarParteProovedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        CargaProveedor();
        CargaParte();
    }

    private void CargaProveedor() {
        ResultSet proveedores = Statements.getProveedores();
        try {
            while (proveedores.next()) {
                modelProveedores.addElement(proveedores.getString("nombre"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(jdIAgregarParte.class.getName()).log(Level.SEVERE, null, ex);
        }

        listProveedores.setModel(modelProveedores);
    }

    private void CargaParte() {
        ResultSet parte = Statements.getParte();
        try {
            while (parte.next()) {
                modelParte.addElement(parte.getString("nombreParte"));
                modelParteIds.addElement(parte.getInt("idParte"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(jdIAgregarParte.class.getName()).log(Level.SEVERE, null, ex);
        }

        listPartes.setModel(modelParte);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtextPrecioProovedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextPorcentajeGanacia = new javax.swing.JTextField();
        jTextPrecioCliente = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnAsociar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPartes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProveedores = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Precio Proovedor");

        jLabel4.setText("% Ganancia");

        jLabel5.setText("Precio Cliente");

        jTextPrecioCliente.setEditable(false);

        btnCalcular.setText("Calcular Precio Cliente");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnAsociar.setBackground(new java.awt.Color(0, 255, 153));
        btnAsociar.setText("Asociar Parte con Proveedor");
        btnAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarActionPerformed(evt);
            }
        });

        listPartes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listPartes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPartesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPartes);

        listProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listProveedores);

        jLabel1.setText("Partes");

        jLabel2.setText("Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtextPrecioProovedor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextPorcentajeGanacia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextPrecioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAsociar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextPrecioProovedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPorcentajeGanacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrecioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addGap(18, 18, 18)
                .addComponent(btnAsociar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        Calcular();

    }//GEN-LAST:event_btnCalcularActionPerformed

    private boolean Calcular() {
        try {
            String Porcentaje = jTextPorcentajeGanacia.getText();
            String PrecioProveedor = jtextPrecioProovedor.getText();
            Revisiones.tamanoString(Porcentaje, 100);
            Revisiones.tamanoString(PrecioProveedor, 100);
            int IntPorcentaje = Revisiones.esEntero(Porcentaje);
            int IntPrecioProveedor = Revisiones.esEntero(PrecioProveedor);
            int precio = IntPrecioProveedor + IntPrecioProveedor * IntPorcentaje / 100;
            jTextPrecioCliente.setText("" + precio);
            return true;

        } catch (Exception e) {
            return false;
        }
    }

    private void btnAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarActionPerformed
        if (Calcular()) {
            try {
                String Porcentaje = jTextPorcentajeGanacia.getText();
                String PrecioProveedor = jtextPrecioProovedor.getText();
                String PrecioCliente = jTextPrecioCliente.getText();
                int Parte = (int)modelParteIds.getElementAt(listPartes.getSelectedIndex());
                String Proveedor = listProveedores.getSelectedValue().toString();
                Statements.IsertarRelacionProveedorParte(Porcentaje, PrecioProveedor, PrecioCliente, Parte, Proveedor);

            } catch (Exception e) {
                Revisiones.ErrorSelecionDeListas("Parte, Proveedor");
                return;
            }
        }


    }//GEN-LAST:event_btnAsociarActionPerformed

    private void listPartesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPartesValueChanged
        System.out.println("CLICK");
    }//GEN-LAST:event_listPartesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdAsociarParteProovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdAsociarParteProovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdAsociarParteProovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdAsociarParteProovedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdAsociarParteProovedor dialog = new jdAsociarParteProovedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextPorcentajeGanacia;
    private javax.swing.JTextField jTextPrecioCliente;
    private javax.swing.JTextField jtextPrecioProovedor;
    private javax.swing.JList listPartes;
    private javax.swing.JList listProveedores;
    // End of variables declaration//GEN-END:variables
}
